### PR TITLE
use posframe to show documentation

### PR DESCRIPTION
**Pull request by nicehiro**

### CODE REVIEW

**Comment by proofit404** [comment]
Hi, thanks for your contribution!

* Should it be melpa dependency?
* Should it be configured to use it or not?
* What would happen if posframe isn't available?

Best regards,
Artem.

**Comment by nicehiro** [comment]
> Hi, thanks for your contribution!
> 
> * Should it be melpa dependency?
> * Should it be configured to use it or not?
> * What would happen if posframe isn't available?
> 
> Best regards,
> Artem.

Hi, your work was really help me a lot!

- Yes, this is [repo](https://github.com/tumashu/posframe/tree/bfd2e55219e0911980f4ea97b5995ce8553dce60)

- If someone want to use posframe to show doc, just set `anaconda-mode-use-posframe-show-doc` to `t`

- Just like old one.

Hope you can test before merging it.

screenshot:
image

**Comment by CeleritasCelery** [comment]
Thanks. This looks really nice.

**Comment by brtsay** [comment]
The versions of posframe on GNU and MELPA require Emacs 26, so this does (might?) break anaconda-mode for anyone using Emacs 25 (the built-in emacs for Ubuntu 18.04 LTS) or below and installing via `list-packages`

**Comment by CeleritasCelery** [comment]
That is a fair point. But installing the package will not cause any issues unless you try to actually execute it. And since it is off by default we should be okay to leave the minimum emacs version at 25.

**Comment by brtsay** [comment]
Thanks for the quick reply! There may be something off with my config, but anaconda-mode now shows up as an incompatible package for me using Emacs 25 due to its posframe dependency
image

**Comment by CeleritasCelery** [comment]
Oh that is an problem. Would you please open a new issue so we can track this properly?

**Comment by brtsay** [comment]
Got it, I opened up an issue #367

**Pull request merged**
